<main class="bd-masthead cebu-fuente-circle" id="content" role="main">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 col-md-12 mx-auto my-5">
                <div class="text-center mb-4">
                    <img src="<?php echo $this->basePath('asset/img/jim.jpg'); ?>" class="rounded img-fluid img-border" alt="Jimvirle E. Calago">
                </div>
                <h1 class="mb-3 text-light text-center text-shadow">Jimvirle E. Calago</h1>
                <h2 class="mb-3 text-light text-center text-shadow">Senior Full Stack Developer</h2>
                <p class="lead text-center text-shadow">
                    <a class="text-light icon-link" href="http://cv.jinexus.com" target="_blank"><i class="fas fa-code"></i></a>&nbsp;&nbsp;
                    <a class="text-light icon-link" href="https://stackoverflow.com/users/2651039/jinexus" target="_blank"><i class="fab fa-stack-overflow"></i></a>&nbsp;&nbsp;
                    <a class="text-light icon-link" href="https://www.linkedin.com/in/jinexus/" target="_blank"><i class="fab fa-linkedin"></i></a>&nbsp;&nbsp;
                    <a class="text-light icon-link" href="https://github.com/JiNexus" target="_blank"><i class="fab fa-github-square"></i></a>&nbsp;&nbsp;
                    <a class="text-light icon-link" href="https://twitter.com/JiNexus" target="_blank"><i class="fab fa-twitter-square"></i></a>&nbsp;&nbsp;
                    <a class="text-light icon-link" href="https://plus.google.com/+JinFur%C4%ABkusu" target="_blank"><i class="fab fa-google-plus-square"></i></a>&nbsp;&nbsp;
                    <a class="text-light icon-link" href="https://www.facebook.com/JOptionPane" target="_blank"><i class="fab fa-facebook-square"></i></a>
                </p>
            </div>
        </div>
    </div>
    <div class="cover-scrollspy"><i class="fas fa-chevron-down"></i></div>
</main>
<div class="masthead-followup row m-0 border border-white">
    <div class="col-12 col-md-12 p-3 p-md-5 bg-light border border-white">
        <div class="container">
            <h2 class="text-center mb-5">Hello from the other side!</h2>
            <p class="lead">My name is Jimvirle E. Calago founder of JiNexus Framework.</p>
            <p class="lead">I live in Cebu City, Philippines, and I am a programmer since 2012.</p>
            <p class="lead">DevOps (Development and Operations) with a focus on PHP web applications and cloud-based Ubuntu servers.</p>
            <p class="lead">
                I have worked in many kind of projects and experienced in building large custom MVC web applications in PHP, using frameworks like Zend Framework, Zend Expressive,
                Apigility, JiNexus Framework, Doctrine ORM, Code Igniter, Phalcon and WordPress.
                Currently I'm focusing on back-end web applications in PHP and MySQL, I also like to venture out into the Bootstrap based front-end world using HTML, CSS and JavaScript.
                And sometimes one needs to experiment with other technologies and I've done this with Python, PostgreSQL and SQLite.
            </p>
            <p class="lead">
                I am one of the thousands of programmers who support and loves open source software, and I contribute with it whenever I can, providing new features, bug fixes or even improving documentation.
                And right now I want to try something new, something that peaks my interest, something worthwhile to do and I have decided to create my own modular, lightweight
                and easy to use PHP MVC framework. And throughout the time I will do my best to improve my knowledge in programming and maintain the best practices and apply the right
                design patterns to my open source project. But amidst all that, I hope that you enjoy using it as much as I enjoyed making it.
            </p>
            <p class="lead">
                This project is open to all contributors who loves open source projects and wants to contribute on it, it will be a great privilege to work with various and intelligent people across the globe.
            </p>
            <br>
            <hr>
            <br>
            <blockquote class="blockquote lead text-right">
                <p class="mb-0">"The fact that I don't believe that I'm better than anyone else gives me an inevitable sense of superiority."</p>
                <footer class="blockquote-footer">Jimvirle E. Calago<cite title="Source Title"> Senior Full Stack Developer</cite></footer>
            </blockquote>
        </div>
    </div>
</div>