<main class="bd-masthead keep-glass-and-code" id="content" role="main">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 col-md-12 mx-auto my-5">
                <h1 class="mb-3 text-light text-center text-shadow">Contributor Code of Conduct</h1>
            </div>
        </div>
    </div>
    <div class="cover-scrollspy"><i class="fas fa-chevron-down"></i></div>
</main>
<div class="masthead-followup row m-0 border border-white">
    <div class="col-12 col-md-12 p-5 bg-light border border-white">
        <div class="container my-5">
            <p class="lead">
                The JiNexus Framework project adheres to <a href="http://codemanifesto.com/" target="_blank">The Code Manifesto</a> as its guidelines for contributor interactions.
            </p>
            <h4 class="mt-5 mb-3">The Code Manifesto</h4>
            <p class="lead">
                We want to work in an ecosystem that empowers developers to reach their potential — one that encourages growth and effective collaboration.
                A space that is safe for all.
            </p>
            <p class="lead">
                A space such as this benefits everyone that participates in it. It encourages new developers to enter our field.
                It is through discussion and collaboration that we grow, and through growth that we improve.
            </p>
            <p class="lead">
                In the effort to create such a place, we hold to these values:
            </p>
            <ol type="1">
                <li class="lead mb-2">
                    <u>Discrimination limits us.</u>
                    This includes discrimination on the basis of race, gender, sexual orientation, gender identity, age, nationality,
                    technology and any other arbitrary exclusion of a group of people.
                </li>
                <li class="lead mb-2">
                    <u>Boundaries honor us.</u>
                    Your comfort levels are not everyone’s comfort levels. Remember that, and if brought to your attention, heed it.
                </li>
                <li class="lead mb-2">
                    <u>We are our biggest assets.</u>
                    None of us were born masters of our trade. Each of us has been helped along the way. Return that favor, when and where you can.
                </li>
                <li class="lead mb-2">
                    <u>We are resources for the future.</u>
                    As an extension of #3, share what you know. Make yourself a resource to help those that come after you.
                </li>
                <li class="mb-2">
                    <p class="lead">
                        <u>Respect defines us.</u>
                        Treat others as you wish to be treated. Make your discussions, criticisms and debates from a position of respectfulness.
                        Ask yourself, is it true? Is it necessary? Is it constructive? Anything less is unacceptable.
                    </p>
                </li>
                <li class="lead mb-2">
                    <u>Reactions require grace.</u>
                    Angry responses are valid, but abusive language and vindictive actions are toxic.
                    When something happens that offends you, handle it assertively, but be respectful.
                    Escalate reasonably, and try to allow the offender an opportunity to explain themselves, and possibly correct the issue.
                </li>
                <li class="lead mb-2">
                    <u>Opinions are just that: opinions.</u>
                    Each and every one of us, due to our background and upbringing, have varying opinions. The fact of the matter, is that is perfectly acceptable.
                    Remember this: if you respect your own opinions, you should respect the opinions of others.
                </li>
                <li class="lead mb-2">
                    <u>To err is human.</u>
                    You might not intend it, but mistakes do happen and contribute to build experience.
                    Tolerate honest mistakes, and don't hesitate to apologize if you make one yourself.
                </li>
            </ol>
        </div>
    </div>
</div>