<main class="bd-masthead code-in-the-dark" id="content" role="main">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 col-md-12 mx-auto my-5">
                <h1 class="mb-3 text-light text-center text-shadow">Credits</h1>
            </div>
        </div>
    </div>
    <div class="cover-scrollspy"><i class="fas fa-chevron-down"></i></div>
</main>
<div class="masthead-followup row m-0 border border-white">
    <div class="col-12 col-md-12 p-3 p-md-5 bg-light border border-white">
        <div class="container">
            <p class="lead">
                In my entire years of programming, before I created JiNexus Framework, I've been using various and different kinds of PHP framework and open-source projects—even up to this days.
                And I acknowledge those technologies on helping me throughout the time and mold me to attained the knowledge that I have right now. Those experiences gives me a depth of understanding
                about S.O.L.I.D principles and different kinds of Design Patterns. Below is the following short list were JiNexus Framework are inspired by.
            </p>
            <ul>
                <li class="lead mb-2">
                    <a href="https://framework.zend.com/" target="_blank">Zend Framework</a> - Not all but most of JiNexus Framework components are based or highly influenced by Zend.
                </li>
                <li class="lead mb-2">
                    <a href="http://designpatternsphp.readthedocs.io/en/latest/" target="_blank">DesignPatternsPHP</a> - JiNexus Framework referenced the best practices
                    and design pattern from DesignPatternsPHP.
                </li>
                <li class="lead mb-2">
                    <a href="https://scotch.io/bar-talk/s-o-l-i-d-the-first-five-principles-of-object-oriented-design" target="_blank">S.O.L.I.D Principles</a>
                    - JiNexus Framework aims to be come easily be extended, modified, tested, and refactored without any problems by adhering from the guidelines
                    of S.O.L.I.D Principles.
                </li>
                <li class="lead mb-2">
                    <a href="https://www.php-fig.org/psr/" target="_blank">PHP Standards Recommendations</a> - JiNexus Framework referenced a standardization approach for PHP from PSR.
                </li>
                <li class="lead mb-2">
                    <a href="https://getbootstrap.com" target="_blank">Bootstrap 4</a> - JiNexus Framework website is currently using the Bootstrap 4 docs.css theme.
                    I did some research if I am allowed to use their docs.css in my open-source or commercial projects and since docs.css is considered being part
                    of the Bootstrap package and falls under the same license as the rest of the framework. Yes! they allow it to be use, you may check their conversation
                    in this <a href="https://github.com/twbs/bootstrap/issues/7280" target="_blank">thread</a>.
                </li>
            </ul>
            <p class="lead">Thank you, open source.</p>
            <p class="lead border-top pt-2">
                And a special thanks to <a href="https://www.linkedin.com/in/ivan-maglasang-988296101/" target="_blank">Ivan Maglasang</a> for helping me out in putting life
                on JiNexus Framework's logo.
            </p>
        </div>
    </div>
</div>