<main class="bd-masthead black-and-white-keep-calm" id="content" role="main">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 col-md-12 mx-auto my-5">
                <h1 class="mb-3 text-light text-center text-shadow">BSD 3-Clause License</h1>
            </div>
        </div>
    </div>
    <div class="cover-scrollspy"><i class="fas fa-chevron-down"></i></div>
</main>
<div class="masthead-followup row m-0 border border-white">
    <div class="col-12 col-md-12 p-3 p-md-5 bg-light border border-white">
        <div class="container">
            <p class="lead">
                Copyright (c) 2018, Jimvirle Calago (JiNexus) jimvirle@gmail.com All rights reserved.
            </p>
            <p class="lead">
                Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
            </p>
            <p class="lead">
            <ul>
                <li class="lead mb-2">
                    Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
                </li>
                <li class="lead mb-2">
                    Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
                </li>
                <li class="lead mb-2">
                    Neither the name of Jimvirle Calago nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
                </li>
            </ul>
            <p class="lead">
                THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
                INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
                IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
                OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
                OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
                OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
                EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
            </p>
        </div>
    </div>
</div>