<main class="bd-masthead code-on-laptop" id="content" role="main">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 col-md-12 mx-auto my-5">
                <h1 class="mb-3 text-light text-center text-shadow">Changelog</h1>
            </div>
        </div>
    </div>
    <div class="cover-scrollspy"><i class="fas fa-chevron-down"></i></div>
</main>
<div class="masthead-followup row m-0 border border-white">
    <div class="col-12 col-md-12 p-3 p-md-5 bg-light border border-white">
        <div class="container">
            <div class="border-bottom">
                <h2 class="text-primary mb-4">1.0.0 <small>(2018-07-21)</small></h2>
                <h4>Added</h4>
                <ul>
                    <li class="lead mb2">Nothing.</li>
                </ul>
                <h4>Deprecated</h4>
                <ul>
                    <li class="lead mb2">Nothing.</li>
                </ul>
                <h4>Removed</h4>
                <ul>
                    <li class="lead mb2">Nothing.</li>
                </ul>
                <h4>Fixed</h4>
                <ul>
                    <li class="lead mb2">Nothing.</li>
                </ul>
            </div>
        </div>
    </div>
</div>