<main class="bd-masthead space stars" id="content" role="main" style="min-height: 39.2rem;">
    <?php echo $this->render('layout/partial/stars'); ?>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 col-md-12 order-md-1 text-center text-md-left pr-md-5">
                <h1 class="my-5 text-primary text-shadow text-center">Lost in Space?</h1>
                <h2 class="text-light text-shadow text-center">A 404 error occurred</h2>
                <h3 class="text-light text-shadow text-center">Page not found</h3>
                <p class="lead text-light text-shadow text-center">The requested URL could not be matched by routing.</p>
                <h4 class="text-light text-shadow text-center">No Exception available</h4>
            </div>
        </div>
    </div>
</main>