<div class="col-12 col-md-3 col-xl-2 bd-sidebar mt-4 mt-md-0">
    <!--<form class="jf-search d-flex align-items-center">
        <input type="search" class="form-control" id="search-input" placeholder="Search..." aria-label="Search for..." autocomplete="off">
        <button class="btn btn-link bd-search-docs-toggle d-md-none p-0 ml-3" type="button" data-toggle="collapse" data-target="#bd-docs-nav" aria-controls="bd-docs-nav" aria-expanded="false" aria-label="Toggle docs navigation">
            <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 30 30" width="30" height="30" focusable="false">
                <title>Menu</title>
                <path stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-miterlimit="10" d="M4 7h22M4 15h22M4 23h22"/>
            </svg>
        </button>
    </form>-->
    <button class="btn btn-link bd-search-docs-toggle d-md-none p-0 ml-3" type="button" data-toggle="collapse" data-target="#bd-docs-nav" aria-controls="bd-docs-nav" aria-expanded="false" aria-label="Toggle docs navigation">
        <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 30 30" width="30" height="30" focusable="false">
            <title>Menu</title>
            <path stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-miterlimit="10" d="M4 7h22M4 15h22M4 23h22"/>
        </svg>
    </button>
    <nav class="collapse bd-links" id="bd-docs-nav">
        <div class="bd-toc-item<?php echo (isset($this->mainSidebar['active']) && in_array('getting-started', $this->mainSidebar['active'])) ? ' active' : ''; ?>">
            <a class="bd-toc-link" href="<?php echo $this->url('application.documentation.getting-started'); ?>">
                Getting Started
            </a>
            <ul class="nav bd-sidenav ml-3">
                <li class="<?php echo (isset($this->mainSidebar['active']) && in_array('introduction', $this->mainSidebar['active'])) ? 'active bd-sidenav-active' : ''; ?>">
                    <a href="<?php echo $this->url('application.documentation.getting-started.introduction'); ?>">
                        Introduction
                    </a>
                </li>
                <li class="<?php echo (isset($this->mainSidebar['active']) && in_array('installation', $this->mainSidebar['active'])) ? 'active bd-sidenav-active' : ''; ?>">
                    <a href="<?php echo $this->url('application.documentation.getting-started.installation'); ?>">
                        Installation
                    </a>
                </li>
            </ul>
        </div>
        <div class="bd-toc-item<?php echo (isset($this->mainSidebar['active']) && in_array('walkthrough', $this->mainSidebar['active'])) ? ' active' : ''; ?>">
            <a class="bd-toc-link" href="<?php echo $this->url('application.documentation.walkthrough'); ?>">
                Walkthrough
            </a>
            <ul class="nav bd-sidenav ml-3">
                <li class="<?php echo (isset($this->mainSidebar['active']) && in_array('introduction', $this->mainSidebar['active'])) ? 'active bd-sidenav-active' : ''; ?>">
                    <a href="<?php echo $this->url('application.documentation.walkthrough.introduction'); ?>">
                        Introduction
                    </a>
                </li>
                <li class="<?php echo (isset($this->mainSidebar['active']) && in_array('module-manager', $this->mainSidebar['active'])) ? 'active bd-sidenav-active' : ''; ?>">
                    <a href="<?php echo $this->url('application.documentation.walkthrough.module-manager'); ?>">
                        Module Manager
                    </a>
                </li>
                <li class="<?php echo (isset($this->mainSidebar['active']) && in_array('controller', $this->mainSidebar['active'])) ? 'active bd-sidenav-active' : ''; ?>">
                    <a href="<?php echo $this->url('application.documentation.walkthrough.controller'); ?>">
                        Controller
                    </a>
                </li>
                <li class="<?php echo (isset($this->mainSidebar['active']) && in_array('route', $this->mainSidebar['active'])) ? 'active bd-sidenav-active' : ''; ?>">
                    <a href="<?php echo $this->url('application.documentation.walkthrough.route'); ?>">
                        Route
                    </a>
                </li>
                <li class="<?php echo (isset($this->mainSidebar['active']) && in_array('http-request', $this->mainSidebar['active'])) ? 'active bd-sidenav-active' : ''; ?>">
                    <a href="<?php echo $this->url('application.documentation.walkthrough.http-request'); ?>">
                        Http Request
                    </a>
                </li>
                <li class="<?php echo (isset($this->mainSidebar['active']) && in_array('view', $this->mainSidebar['active'])) ? 'active bd-sidenav-active' : ''; ?>">
                    <a href="<?php echo $this->url('application.documentation.walkthrough.view'); ?>">
                        View
                    </a>
                </li>
                <li class="<?php echo (isset($this->mainSidebar['active']) && in_array('config', $this->mainSidebar['active'])) ? 'active bd-sidenav-active' : ''; ?>">
                    <a href="<?php echo $this->url('application.documentation.walkthrough.config'); ?>">
                        Config
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="d-block d-md-none"><hr></div>
</div>