<footer class="bd-footer text-muted text-center">
    <div class="container-fluid p-3 p-md-5">
        <ul class="bd-footer-links">
            <li><a href="https://github.com/jinexus-framework" target="_blank">GitHub</a></li>
            <li><a href="<?php echo $this->url('application.about.author'); ?>">Author</a></li>
            <li><a href="<?php echo $this->url('application.about.conduct'); ?>">Conduct</a></li>
            <li><a href="<?php echo $this->url('application.about.credits'); ?>">Credits</a></li>
            <li><a href="<?php echo $this->url('application.about.license'); ?>">License</a></li>
            <li><a href="mailto:jimvirle@gmail.com?Subject=Hello%from%20the%20other%20side!">Contact Us</a></li>
        </ul>
        <p>A birth is built not born. This project is maintained by <a href="https://twitter.com/JiNexus" target="_blank" rel="noopener">@JiNexus</a></p>
        <p>Current Version 1.0.0. Code licensed <a href="#" target="_blank" rel="license noopener">BSD-3-Clause</a>.</p>
        <p>&copy; <?php echo date('Y'); ?> by JiNexus Framework. All rights reserved.</p>
    </div>
</footer>