<!DOCTYPE html>
<html lang="en">
    <head>
        <title>JiNexus Framework</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <link href="<?php echo $this->basePath('asset/img/favicon.ico'); ?>" rel="shortcut icon" type="image/x-icon" />
        <link href="<?php echo $this->basePath('asset/lib/normalize/8.0.0/normalize.css'); ?>" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('asset/lib/bootstrap/4.0.0/css/bootstrap.min.css'); ?>" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('asset/lib/fontawesome/5.1.0/css/all.css'); ?>" media="screen" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('asset/css/docs.min.css'); ?>" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('asset/css/stars.css'); ?>" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('asset/css/core.css'); ?>" media="screen" rel="stylesheet" type="text/css" />
        <!-- Google Tag Manager -->
        <script>
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-W4T7G5M');
        </script>
        <!-- End Google Tag Manager -->
    </head>
    <body>
        <!-- Google Tag Manager (noscript) -->
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W4T7G5M" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <!-- End Google Tag Manager (noscript) -->
        <?php echo $this->render('layout/header'); ?>
        <?php echo $this->content(); ?>
        <?php echo $this->render('layout/footer'); ?>
        <script type="text/javascript" src="<?php echo $this->basePath('asset/lib/jquery/3.3.1/jquery.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('asset/lib/bootstrap/4.0.0/js/bootstrap.bundle.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('asset/js/docs.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('asset/lib/bootstrap/4.0.0/js/ie-emulation-modes-warning.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('asset/lib/holder/2.9.0/holder.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('asset/js/core.js'); ?>"></script>
    </body>
</html>